Created main input component
GSG-G9/ws-booker pull request #37
Opened 2021-03-28 17:56 UTC by Sondos-Alalami

Relates #13

- Created main input component with needed props (style, placeholder, label, value, onChange, type).
- Type prop defines the type of input (text, number, date range, time range, password).
- Handle prop types and default values.

2021-03-29 09:02 UTC, Israa91 requested changes
Good job !
I think you should add a case when the input type is Password

2021-03-29 09:02 UTC, alaa-sahloub submitted a review, later dismissed

2021-03-29 09:16 UTC, Israa91 commented on src/components/CommonComponents/Input/index.js
> +            prefix={<SearchOutlined style={{ color: '#929292' }} />}
I suggest using 
```
     suffix={<SearchOutlined style={{ color: '#929292' }} />}
```
instead of prefix to match figma design

2021-03-29 13:32 UTC, Israa91 approved these changes

2021-03-30 07:14 UTC, alaa-sahloub approved these changes

2021-03-30 07:16 UTC, lina-jamal approved these changes

2021-03-30 07:16 UTC, merged