Edit User Data
GSG-G9/ws-booker pull request #67
Opened 2021-04-02 15:23 UTC by alaa-sahloub

Relates #61

2021-04-03 22:08 UTC, lina-jamal commented on src/firebase/EditUserData.js
> +    await response.update({
please validate the data before update iy

2021-04-04 06:48 UTC, Sondos-Alalami requested changes

2021-04-04 06:48 UTC, Sondos-Alalami commented on src/firebase/EditUserData.js
> +  bookCapacity
I think ( id, name, number, image, coverImage) are the only data needed here, the other ones will not be edited by the user.
and please rename the parameters with lower case for the first letter.

2021-04-05 09:45 UTC, Israa91 approved these changes

2021-04-05 09:45 UTC, Sondos-Alalami approved these changes

2021-04-05 09:46 UTC, lina-jamal approved these changes

2021-04-05 09:46 UTC, merged